#!/bin/fish

## trim function
function trim
    set -l var $argv
    set var (string trim $var)
    echo $var
end

set gitTopLevel (git rev-parse --show-toplevel);
set mainBranch (__git.default_branch);
set configFile (trim (git config --list --show-origin | tail -n 1 | grep -o "\/[^[:space:]]\+[[:space:]]" | grep -o "^[^[:space:]]\+"));
set repoName (basename (cat $configFile | grep "url = " | grep -o "\/.\+"));
set templateFile (echo $gitTopLevel/.azuredevops/pull_request_template.md);
set descTempFile /tmp/description.md;
set lastDescTempFile /tmp/lastDescription.md;
set prLogTempFile /tmp/pr.log;
set currentBranch (__git.current_branch);
set taskNumber (echo "$currentBranch" | grep -e "[0-9]\+" -o);

# verifica se a task number tem mais de uma sequencia de números
if echo $taskNumber | grep -qE "[0-9]{2,}"
  # Se tiver, separa os dois números
  set subTaskNumber (echo $taskNumber | grep -oE "[0-9]{2,}" | tail -n 1)
  set taskNumber (echo $taskNumber | grep -oE "[0-9]{2,}" | head -n 1)
end

# Verifica se a branch existe no remoto
if git show-ref --quiet refs/remotes/origin/$currentBranch
  echo "A branch $currentBranch não existe no remoto. Por favor, crie-a antes de criar o PR."
  git push -u origin $currentBranch
end

# Verifica se tem commits para enviar ao remoto
if not git diff --cached --quiet origin/$__git.current_branch
  echo "Você tem commits pendentes. Por favor, envie-os ao servidor antes de criar o PR."
  exit 1
end

if test -z "$taskNumber"
  echo "Não consegui identificar o número da task no nome do branch atual ($currentBranch)."
  echo "Por favor, informe o número da task manualmente:"
  read -P "" taskNumber
  echo
end

if test -z "$subTaskNumber"
  echo "Não consegui identificar o número da sub task no nome do branch atual ($currentBranch)."
  echo "Por favor, informe o número da sub task manualmente ou deixe o campo em branco, caso não tenha sub task:"
  read -P "" subTaskNumber
  echo
end

set titlePrefix "#$taskNumber"
if test -z "$subTaskNumber"
  echo "Qual o título do seu PR? Vamos adicionar o número da task ($taskNumber) ao início dele"
else
  echo "Qual o título do seu PR? Vamos adicionar os números da task ($taskNumber) e da sub task ($subTaskNumber) ao início dele"
  set -a titlePrefix "#$subTaskNumber"
end
read -l -P "" title

if test -z "$title"
  echo
  echo "Título não pode ser vazio. Saindo do programa."
  exit 1
end

# backup do último pr
mv $descTempFile $lastDescTempFile

# cria arquivo tmp para descrição apenas com o número da task
echo \#$taskNumber > $descTempFile
echo \#$subTaskNumber >> $descTempFile

# concatena o template ao final do arquivo tmp para descrição
if test -f $templateFile
  cat $templateFile >> $descTempFile
end

# abre o arquivo temporário para edição
$EDITOR $descTempFile

# prepara o conteúdo do arquivo editado para ser transmitido via linha de comando
set description
while read -l line
  set -a description "$line "
end < $descTempFile

BROWSER=google-chrome-stable az repos pr create --draft --title "$titlePrefix $title" -t $mainBranch -r $repoName -d $description --open > $prLogTempFile;

# set repoUrl (cat $prLogTempFile | jq .repository.webUrl | sed "s/\"//g")
# set prId (cat $prLogTempFile | jq .codeReviewId)
# set prUrl "$repoUrl/pullrequest/$prId"

# echo $prUrl

# google-chrome-stable $prUrl
