#!/bin/fish

## trim function
function trim
    set -l var $argv
    set var (string trim $var)
    echo $var
end

set gitTopLevel (git rev-parse --show-toplevel);
# echo "gitTopLevel: $gitTopLevel"
set mainBranch (__git.default_branch);
# echo "mainBranch: $mainBranch"
set configFile (trim (git config --list --show-origin | tail -n 1 | grep -o "\/[^[:space:]]\+[[:space:]]" | grep -o "^[^[:space:]]\+"));
# echo configFile: "$configFile"
set repoName (basename (cat $configFile | grep "url = " | grep -o "\/.\+"));
# echo repoName: $repoName
set templateFile (echo $gitTopLevel/.azuredevops/pull_request_template.md);
set descTempFile /tmp/description.md;
set lastDescTempFile /tmp/lastDescription.md;
set prLogTempFile /tmp/pr.log;
set currentBranch (__git.current_branch);
set taskNumber (echo "$currentBranch" | grep -e "[0-9]\+" -o);

# Verifica se a branch existe no remoto
if git show-ref --quiet refs/remotes/origin/$currentBranch
  echo "A branch $currentBranch não existe no remoto. Por favor, crie-a antes de criar o PR."
  git push -u origin $currentBranch
end

# Verifica se tem commits para enviar ao remoto
if not git diff --cached --quiet origin/$__git.current_branch
  echo "Você tem commits pendentes. Por favor, envie-os ao servidor antes de criar o PR."
  exit 1
end

if test -z "$taskNumber"
  echo "Não consegui identificar o número da task no nome do branch atual ($currentBranch)."
  echo "Por favor, informe o número da task manualmente:"
  read -P "" taskNumber
  echo
end

echo "Qual o título do seu PR? Vamos adicionar o número da task ($taskNumber) ao início dele"
read -l -P "" title

if test -z "$title"
  echo
  echo "Título não pode ser vazio. Saindo do programa."
  exit 1
end

# backup do último pr
mv $descTempFile $lastDescTempFile

# cria arquivo tmp para descrição apenas com o número da task
echo \#$taskNumber > $descTempFile

# concatena o template ao final do arquivo tmp para descrição
if test -f $templateFile
  cat $templateFile >> $descTempFile
end

# abre o arquivo temporário para edição
$EDITOR $descTempFile

# prepara o conteúdo do arquivo editado para ser transmitido via linha de comando
set description
while read -l line
  set -a description "$line "
end < $descTempFile

az repos pr create --draft --title "#$taskNumber $title" -t $mainBranch -r $repoName -d $description > $prLogTempFile;

set repoUrl (cat $prLogTempFile | jq .repository.webUrl | sed "s/\"//g")
set prId (cat $prLogTempFile | jq .codeReviewId)
set prUrl "$repoUrl/pullrequest/$prId"

echo $prUrl

google-chrome-stable $prUrl
